name: Push latest
on:
  push:
    branches:
      - develop
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@master
    - name: Construye imagen
      run: docker build --tag islasgeci/cli_guadalupe_data:latest --tag islasgeci/cli_guadalupe_data:${GITHUB_SHA:0:4} .
    - name: Verifica el formato
      run: docker run islasgeci/cli_guadalupe_data:latest make check
    - name: Corre pruebas y evalúa cobertura
      run: docker run islasgeci/cli_guadalupe_data:latest make coverage
    - name: Create/Update tag
      uses: rickstaa/action-create-tag@main
      with:
        tag: "latest"
        message: "Latest release"
        force_push_tag: true
    - name: Docker log-in
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - name: Sube latest a Docker Hub
      run: docker push islasgeci/cli_guadalupe_data:latest
    - name: Sube sha a Docker Hub
      run: docker push islasgeci/cli_guadalupe_data:${GITHUB_SHA:0:4}
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
        skip_existing: true
  mutants:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@master
    - name: Construye imagen
      run: docker build --tag islasgeci/cli_guadalupe_data:latest
    - name: Evalúa resistencia a mutaciones
      run: docker run islasgeci/cli_guadalupe_data:latest make mutants
